"""
PHASE 4 — Backend API (FastAPI)
==================================
Three endpoints:
  GET  /regions          -> list of supported regions/crops (stub data for now)
  POST /predict-risk     -> takes crop+region+date, returns a risk score
  POST /advisory         -> takes a risk output, returns a RAG-grounded advisory

Run:
    uvicorn backend.main:app --reload
Then visit http://127.0.0.1:8000/docs for interactive API docs (auto-generated by FastAPI).
"""

import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from fastapi import FastAPI
from pydantic import BaseModel
import joblib

from rag.generate_advisory import generate_with_rag

app = FastAPI(title="Pest Risk Prediction & Advisory API")

# TODO: replace with real region list once you've picked your target districts
STUB_REGIONS = [
    {"region": "Guntur", "crops": ["Rice", "Chilli", "Cotton"]},
    {"region": "Krishna", "crops": ["Rice", "Sugarcane"]},
]


class RiskRequest(BaseModel):
    crop: str
    region: str
    temp_mean_c: float
    humidity_pct: float
    rain_mm: float
    soil_n: float = 0
    soil_p: float = 0
    soil_k: float = 0
    soil_ph: float = 7.0


class AdvisoryRequest(BaseModel):
    crop: str
    region: str
    risk_score: float
    pest_name: str = ""


@app.get("/regions")
def get_regions():
    return {"regions": STUB_REGIONS}


@app.post("/predict-risk")
def predict_risk(req: RiskRequest):
    try:
        model = joblib.load("ml/baseline_model.pkl")
        features = [[
            req.temp_mean_c, req.humidity_pct, req.rain_mm,
            req.soil_n, req.soil_p, req.soil_k, req.soil_ph,
        ]]
        risk_prob = model.predict_proba(features)[0][1]
    except FileNotFoundError:
        # Model not trained yet — return a placeholder so the API doesn't crash
        # during early frontend development. Train the model first: see ml/train_baseline.py
        risk_prob = 0.5

    return {
        "crop": req.crop,
        "region": req.region,
        "risk_score": round(risk_prob, 3),
        "risk_level": "high" if risk_prob >= 0.7 else "moderate" if risk_prob >= 0.4 else "low",
        "contributing_factors": {
            "humidity_pct": req.humidity_pct,
            "rain_mm": req.rain_mm,
            "temp_mean_c": req.temp_mean_c,
        },
    }


@app.post("/advisory")
def get_advisory(req: AdvisoryRequest):
    question = (
        f"The pest risk for {req.crop} in {req.region} is currently {req.risk_score:.0%}"
        f"{f' (suspected pest: {req.pest_name})' if req.pest_name else ''}. "
        f"What should the farmer do?"
    )
    try:
        advisory_text = generate_with_rag(question)
    except Exception as e:
        advisory_text = f"[Advisory generation not yet configured: {e}]"

    return {"crop": req.crop, "region": req.region, "advisory": advisory_text}
